### ISSUE TITLE
IR chapter references

### ISSUE THREAD

**Issue by ilkkarinne** [inspire-eu-validation/ats-metadata#18]
To which document do the IR references in the ats-metadata tests point to?

Example: the test A.02.IR221.title has the reference to Chapter 2.2.1 of the "Implementing Directive 2007/2/EC of the European Parliament and of the Council as regards metadata", but when I open the linked document (http://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32008R1205&from=EN) there is no Chapter 2.2.1. Instead the title requirement is discussed in Part B, "1. Identification",  "1.1 Resource title".

Similar IR references are in almost every ats-metadata test, which is also reflected in the test naming.

Can you shed any light on this @pvgenuchten?

**Comment by pvgenuchten** [comment]
@ilkkarinne the numbering seems indeed inconsistent with the IR document. I noticed it does align with the paragraphs of the Technical Guidelines. So I guess I made an error when setting up the numbering and didn't realise the error in the approach while creating the issues. I would suggest to improve the numbering to follow IR naming conventions

**Comment by pvgenuchten** [comment]
changed the numbering
