### ISSUE TITLE
Interoperability metadata

### ISSUE THREAD

**Issue by pvgenuchten** [inspire-eu-validation/ats-metadata#4]
In issue https://ies-svn.jrc.ec.europa.eu/issues/2214 some required metadata elements originating from  the data specifications are introduced that currently are not available in the IR and TG metadata. 

How do we manage?
- Similar is already stated in IR/TG metadata, so we can create tests for this in current Test Suite
- Since this is related to metadata and it is in one of the IR/TG's, we should add it to this Test Suite
- This Test Suite tests only this version of the IR/TG, these requierements originate from another IR/TG, so should be in another (version of the) test suite

**Comment by aquaglia** [comment]
I think not to include them would be wrong. They have to be there, perhaps with different deadlines.
At the same time, I am not sure we will be able to define the tests completely.
We could use placeholders, though.

**Comment by pvgenuchten** [comment]
conclusion meeting 9-2-2015 is to create a new repo for interoperability metadata
