### ISSUE TITLE
Wrong ATS names?

### ISSUE THREAD

**Issue by aquaglia** [inspire-eu-validation/ats-metadata#6]
I click on A.27.IR2113.TGR39.date.md but it talks about the language.
Same with some other ATSs.

**Comment by aquaglia** [comment]
A.26.IR2112.TGR38.md.role.md
talks about something else

**Comment by ilkkarinne** [comment]
This is now fixed: A.27.IR2113.TGR39.language is about language and A.26.IR2112.TGR38.md.role is about the role of the metadata point of contact
